<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>regression_models</title>

<script src="site_libs/header-attrs-2.28/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Rodent Analysis</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Analysis
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Report.html">Report</a>
    </li>
    <li>
      <a href="data_clean.html">Data Cleaning</a>
    </li>
    <li>
      <a href="Rat_region.html">Rat Region</a>
    </li>
    <li>
      <a href="rodent_activity.html">Rat Activity</a>
    </li>
    <li>
      <a href="regression_models.html">Regression Models</a>
    </li>
  </ul>
</li>
<li>
  <a href="shiny_apps.html">Shiny App</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">




</div>


<div id="regression_models" class="section level1">
<h1>regression_models</h1>
<p>Yujing Fu, Hanrui Li 2024-11-30</p>
<pre class="r"><code>library(tidyverse)
library(dplyr)
library(ggplot2)
library(lubridate)
library(tidyr)
library(rvest)
library(janitor)
library(modelr)</code></pre>
<pre class="r"><code># data import 
rat_df = read.csv(&quot;data/rat_2020_2024.csv&quot;)
food_scrap_df = 
  read.csv(&quot;data/food_scrap_drop_off.csv&quot;)
zhvi_df = read.csv(&quot;data/ny_zhvi_df_2020_2024.csv&quot;)
zori_df = read.csv(&quot;data/ny_zori_df_2020_2024.csv&quot;)

head(rat_df)</code></pre>
<pre><code>##   inspection_type job_ticket_or_work_order_id    job_id job_progress        bbl
## 1         Initial                    13659068 PC8078519            1 4023290019
## 2         Initial                    13361613 PC7824966            1 3072810182
## 3         Initial                    13599220 PC8056345            1 2033950047
## 4            BAIT                     2941952 PC8141304            5 4104480015
## 5         Initial                    13788881 PC8254435            1 2057930467
## 6      Compliance                    13383745 PC7780758            2 3034140068
##   boro_code block lot house_number      street_name zip_code x_coord y_coord
## 1         4  2329  19        48-03        59 STREET    11377       0       0
## 2         3  7281 182          145 SEABREEZE AVENUE    11224       0       0
## 3         2  3395  47          530  EAST 234 STREET    10470       0       0
## 4         4 10448  15       192-21   JAMAICA AVENUE    11423 1048743  199167
## 5         2  5793 467         3555    OXFORD AVENUE    10463 1009450  262094
## 6         3  3414  68            9    COVERT STREET    11207       0       0
##   latitude longitude  borough        inspection_date             result
## 1 40.73837 -73.90647   Queens 06/05/2023 03:19:22 PM             Passed
## 2 40.57565 -73.97020 Brooklyn 04/05/2022 03:50:52 PM             Passed
## 3 40.89732 -73.86322    Bronx 03/14/2023 08:40:50 AM Failed for Other R
## 4 40.71310 -73.76736   Queens 12/26/2023 12:16:51 PM       Bait applied
## 5 40.88602 -73.90886    Bronx 01/23/2024 04:10:00 PM       Rat Activity
## 6 40.68518 -73.91342 Brooklyn 05/09/2022 03:35:15 PM             Passed
##            approved_date                            location community_board
## 1 06/08/2023 05:06:47 PM                                                   2
## 2 04/08/2022 03:54:46 PM                                                  13
## 3 03/17/2023 02:48:23 PM                                                  12
## 4 12/27/2023 10:10:53 AM (40.713101329334, -73.767362471917)              12
## 5 01/24/2024 11:33:03 AM (40.886019879068, -73.908861936068)               8
## 6 05/12/2022 08:19:56 AM                                                   4
##   council_district census_tract     bin                      nta year month
## 1               26          245 4053773                 Woodside 2023     6
## 2               48        35602 3196597    Coney Island-Sea Gate 2022     4
## 3               11        45101 2019758       Wakefield-Woodlawn 2023     3
## 4               23          482 4222146                   Hollis 2023    12
## 5               11          295 2084152 Riverdale-Spuyten Duyvil 2024     1
## 6               37          401 3078992          Bushwick (East) 2022     5</code></pre>
<pre class="r"><code>head(food_scrap_df)</code></pre>
<pre><code>##         borough                nta_name
## 1      Brooklyn               Bay Ridge
## 2     Manhattan East Midtown-Turtle Bay
## 3     Manhattan          Hell&#39;s Kitchen
## 4     Manhattan East Midtown-Turtle Bay
## 5     Manhattan    Tribeca-Civic Center
## 6 Staten Island St. George-New Brighton
##                                    site_name
## 1             4th Avenue Presbyterian Church
## 2         Dag Hammarskjold Plaza Greenmarket
## 3 Hudson River Park&#39;s Pier 84 at W. 44th St.
## 4                   58th Street Library FSDO
## 5                        Tribeca Greenmarket
## 6                     St. George Greenmarket
##                              site_addr
## 1  6753 4th Avenue, Brooklyn, NY 11220
## 2                  E 47th St &amp; 2nd Ave
## 3 Pier 84 at W. 44th St. near dog park
## 4                 127 East 58th Street
## 5             Greenwich St. &amp; Duane St
## 6            St. Marks Pl and Hyatt St
##                                                                      hosted_by
## 1                                               4th Avenue Presbyterian Church
## 2                                                                      GrowNYC
## 3                                                   Staff at Hudson River Park
## 4                                                                      GrowNYC
## 5                                                                      GrowNYC
## 6 NYC Compost Project Hosted by Snug Harbor Cultural Center &amp; Botanical Garden
##   open_month                                             day_hours
## 1 Year Round        Every day (Start Time: Dawn - End Time:  Dusk)
## 2 Year Round Wednesday (Start Time: 8:00 AM - End Time:  12:30 PM)
## 3 Year Round  Every day (Start Time: 7:00 AM - End Time:  7:00 PM)
## 4 Year Round Wednesdays (Start Time: 7:30 AM - End Time:  1:30 PM)
## 5 Year Round   Saturday (Start Time: 8:00 AM - End Time:  1:00 PM)
## 6 Year Round   Saturday (Start Time: 8:00 AM - End Time:  1:00 PM)
##                       notes
## 1 No meat, bones, or dairy.
## 2                      &lt;NA&gt;
## 3                      &lt;NA&gt;
## 4                      &lt;NA&gt;
## 5                      &lt;NA&gt;
## 6                      &lt;NA&gt;
##                                                                          website
## 1                                                                           &lt;NA&gt;
## 2                                                            grownyc.org/compost
## 3 https://hudsonriverpark.org/the-park/sustainability/community-compost-program/
## 4                                                            grownyc.org/compost
## 5                                                            grownyc.org/compost
## 6                                                                snug-harbor.org
##   boro_cd council_dis  ct2010 bbl bin latitude longitude police_prec object_id
## 1     310          47 3012600  NA  NA 40.63551 -74.02277          68     31263
## 2     106           4 1009000  NA  NA 40.75261 -73.96904          17     31123
## 3     104           3 1012901  NA  NA 40.76346 -74.00025          18     31091
## 4     105           4 1011203  NA  NA 40.76198 -73.96930          18     31084
## 5     101           1 1003900  NA  NA 40.71742 -74.01079           1     30996
## 6     501          49 5000300  NA  NA 40.64197 -74.07793         120     30956
##                 location_point app_android app_i_os assembly_district
## 1 POINT (-74.022767 40.635514)        &lt;NA&gt;     &lt;NA&gt;                51
## 2 POINT (-73.969036 40.752606)        &lt;NA&gt;     &lt;NA&gt;                74
## 3   POINT (-74.00025 40.76346)        &lt;NA&gt;     &lt;NA&gt;                67
## 4    POINT (-73.9693 40.76198)        &lt;NA&gt;     &lt;NA&gt;                73
## 5 POINT (-74.010793 40.717424)        &lt;NA&gt;     &lt;NA&gt;                66
## 6 POINT (-74.077928 40.641967)        &lt;NA&gt;     &lt;NA&gt;                61
##   congress_district dsny_district dsny_section dsny_zone senate_district
## 1                10         BKS10       BKS101       BKS              17
## 2                12          MN06        MN063        MN              28
## 3                12          MN04        MN043        MN              47
## 4                12          MN05        MN052        MN              28
## 5                10          MN01        MN013        MN              27
## 6                11          SI01        SI012        SI              23</code></pre>
<pre class="r"><code>head(zhvi_df)</code></pre>
<pre><code>##   RegionID SizeRank RegionName RegionType StateName State     City
## 1    62080        4      11368        zip        NY    NY New York
## 2    62093        7      11385        zip        NY    NY New York
## 3    62019        9      11208        zip        NY    NY New York
## 4    62046       16      11236        zip        NY    NY New York
## 5    61807       17      10467        zip        NY    NY New York
## 6    62085       18      11373        zip        NY    NY New York
##                                   Metro    CountyName X2020.1.31 X2020.2.29
## 1 New York-Newark-Jersey City, NY-NJ-PA Queens County   528192.6   527257.9
## 2 New York-Newark-Jersey City, NY-NJ-PA Queens County   766285.8   766877.9
## 3 New York-Newark-Jersey City, NY-NJ-PA  Kings County   584069.0   584128.8
## 4 New York-Newark-Jersey City, NY-NJ-PA  Kings County   556447.0   558779.1
## 5 New York-Newark-Jersey City, NY-NJ-PA  Bronx County   431082.0   426699.4
## 6 New York-Newark-Jersey City, NY-NJ-PA Queens County   675125.7   675670.1
##   X2020.3.31 X2020.4.30 X2020.5.31 X2020.6.30 X2020.7.31 X2020.8.31 X2020.9.30
## 1   524266.9   522275.8   521385.9   520385.5   516688.1   510385.4   504947.1
## 2   767261.6   768287.1   768536.4   767880.3   766388.6   764911.0   763249.7
## 3   585511.1   588232.9   591933.8   592971.8   591628.3   589038.7   587388.2
## 4   561201.6   563977.4   566000.7   565868.6   564319.2   562457.2   561660.1
## 5   417166.3   409128.2   404095.7   402165.0   402087.6   401990.7   405016.7
## 6   673500.0   668760.7   664276.7   662083.9   654935.9   644841.3   635070.8
##   X2020.10.31 X2020.11.30 X2020.12.31 X2021.1.31 X2021.2.28 X2021.3.31
## 1    503106.5    503648.4    506265.0   508977.3   512132.8   514154.6
## 2    759656.1    756066.8    753333.5   752381.3   753657.6   756193.4
## 3    586779.6    587397.1    588714.3   590735.8   593778.1   597376.2
## 4    561378.6    562520.3    564734.6   568278.6   572763.3   578465.5
## 5    408095.2    412207.6    416081.1   421889.1   431480.8   444899.4
## 6    630178.7    626333.1    623006.2   618409.3   617337.5   618486.7
##   X2021.4.30 X2021.5.31 X2021.6.30 X2021.7.31 X2021.8.31 X2021.9.30 X2021.10.31
## 1   513545.6   513274.3   512169.7   513647.7   515205.9   517516.9    520167.9
## 2   760293.4   764712.1   768415.4   771259.6   772388.5   773570.8    775890.5
## 3   602246.5   606895.0   609155.7   610491.7   610604.1   613045.0    617421.0
## 4   584991.4   591055.9   594904.9   596912.1   597603.3   597795.9    598878.2
## 5   455437.9   462904.9   461875.1   453605.1   438793.4   421945.6    411599.9
## 6   619560.2   620293.7   617666.3   618197.6   618781.9   619884.8    620588.8
##   X2021.11.30 X2021.12.31 X2022.1.31 X2022.2.28 X2022.3.31 X2022.4.30
## 1    521725.6    521886.5   519710.8   517534.2   516469.2   516859.7
## 2    779431.8    782268.2   783578.9   783441.1   785378.3   788904.9
## 3    623356.3    628199.3   630765.7   631970.0   633731.6   636190.4
## 4    601476.8    604396.6   607793.6   611521.1   616361.0   620093.7
## 5    403827.1    397758.7   394423.8   398191.9   407522.6   413924.8
## 6    619487.9    617252.4   614656.6   614966.0   617660.6   619955.0
##   X2022.5.31 X2022.6.30 X2022.7.31 X2022.8.31 X2022.9.30 X2022.10.31
## 1   516227.9   516353.1   516371.5   514825.7   511602.0    508097.2
## 2   796084.2   804432.2   810063.0   811312.9   807884.0    804876.2
## 3   640465.9   645628.6   649119.5   649810.3   647188.8    644657.8
## 4   622656.0   625384.0   627041.1   627201.2   623448.9    620023.4
## 5   414126.5   412279.0   408672.8   402399.6   392358.9    384807.9
## 6   619968.6   621096.5   619121.3   612323.0   601194.8    591469.8
##   X2022.11.30 X2022.12.31 X2023.1.31 X2023.2.28 X2023.3.31 X2023.4.30
## 1    506580.5    503289.1   497724.8   490815.4   484453.6   477787.1
## 2    802838.2    802151.0   800703.4   798950.1   797761.4   799366.6
## 3    642264.1    641399.5   640105.2   637786.4   636126.6   640210.0
## 4    616886.2    614528.1   610691.6   606678.5   604931.1   608805.4
## 5    380556.4    379171.4   374879.9   373540.1   375699.4   384275.2
## 6    584564.3    577927.4   569925.2   564723.3   561582.7   556310.6
##   X2023.5.31 X2023.6.30 X2023.7.31 X2023.8.31 X2023.9.30 X2023.10.31
## 1   470639.5   465210.9   463377.3   463371.3   462810.6    460771.9
## 2   801223.4   802036.8   801422.6   800283.2   798291.5    797014.0
## 3   648346.8   654695.9   657573.2   657020.5   656315.8    655178.3
## 4   615239.9   621151.8   624614.7   626492.5   627861.0    628682.6
## 5   391838.2   396577.9   399856.9   402236.0   403255.3    400097.0
## 6   545838.3   531434.2   521217.5   513782.0   509985.5    505959.8
##   X2023.11.30 X2023.12.31 X2024.1.31 X2024.2.29 X2024.3.31 X2024.4.30
## 1    457397.8    453086.2   450240.7   448627.2   451705.6   456243.1
## 2    795779.1    795640.7   794282.4   794342.2   797380.4   802193.9
## 3    654648.3    656263.8   658709.2   661959.5   666440.0   670735.0
## 4    629011.8    630674.1   632713.9   635540.9   638623.8   641376.0
## 5    394496.2    386985.9   382000.0   378034.4   377532.6   374809.3
## 6    501444.1    497843.2   493967.4   492163.3   491429.0   492810.0
##   X2024.5.31 X2024.6.30 X2024.7.31 X2024.8.31 X2024.9.30 X2024.10.31
## 1   460893.5   461600.4   461088.3   460451.8   461417.2    461167.7
## 2   805219.7   804711.7   804494.0   806317.1   810315.1    814334.5
## 3   673816.0   674124.7   674583.6   675525.6   677539.8    678312.6
## 4   642619.7   641839.5   641629.1   643184.2   646821.1    650637.9
## 5   372827.7   369063.0   368696.4   369597.6   371425.2    371800.4
## 6   495404.8   497218.9   499719.7   501979.1   503272.5    505398.0</code></pre>
<pre class="r"><code>head(rat_df)</code></pre>
<pre><code>##   inspection_type job_ticket_or_work_order_id    job_id job_progress        bbl
## 1         Initial                    13659068 PC8078519            1 4023290019
## 2         Initial                    13361613 PC7824966            1 3072810182
## 3         Initial                    13599220 PC8056345            1 2033950047
## 4            BAIT                     2941952 PC8141304            5 4104480015
## 5         Initial                    13788881 PC8254435            1 2057930467
## 6      Compliance                    13383745 PC7780758            2 3034140068
##   boro_code block lot house_number      street_name zip_code x_coord y_coord
## 1         4  2329  19        48-03        59 STREET    11377       0       0
## 2         3  7281 182          145 SEABREEZE AVENUE    11224       0       0
## 3         2  3395  47          530  EAST 234 STREET    10470       0       0
## 4         4 10448  15       192-21   JAMAICA AVENUE    11423 1048743  199167
## 5         2  5793 467         3555    OXFORD AVENUE    10463 1009450  262094
## 6         3  3414  68            9    COVERT STREET    11207       0       0
##   latitude longitude  borough        inspection_date             result
## 1 40.73837 -73.90647   Queens 06/05/2023 03:19:22 PM             Passed
## 2 40.57565 -73.97020 Brooklyn 04/05/2022 03:50:52 PM             Passed
## 3 40.89732 -73.86322    Bronx 03/14/2023 08:40:50 AM Failed for Other R
## 4 40.71310 -73.76736   Queens 12/26/2023 12:16:51 PM       Bait applied
## 5 40.88602 -73.90886    Bronx 01/23/2024 04:10:00 PM       Rat Activity
## 6 40.68518 -73.91342 Brooklyn 05/09/2022 03:35:15 PM             Passed
##            approved_date                            location community_board
## 1 06/08/2023 05:06:47 PM                                                   2
## 2 04/08/2022 03:54:46 PM                                                  13
## 3 03/17/2023 02:48:23 PM                                                  12
## 4 12/27/2023 10:10:53 AM (40.713101329334, -73.767362471917)              12
## 5 01/24/2024 11:33:03 AM (40.886019879068, -73.908861936068)               8
## 6 05/12/2022 08:19:56 AM                                                   4
##   council_district census_tract     bin                      nta year month
## 1               26          245 4053773                 Woodside 2023     6
## 2               48        35602 3196597    Coney Island-Sea Gate 2022     4
## 3               11        45101 2019758       Wakefield-Woodlawn 2023     3
## 4               23          482 4222146                   Hollis 2023    12
## 5               11          295 2084152 Riverdale-Spuyten Duyvil 2024     1
## 6               37          401 3078992          Bushwick (East) 2022     5</code></pre>
<pre class="r"><code># clean rat data
rat_tidydf = rat_df |&gt; 
  mutate(inspection_date = substring(inspection_date, 1, 10)) |&gt; 
  mutate(date = as.Date(inspection_date, format = &quot;%m/%d/%Y&quot;)) |&gt; 
  mutate(year = as.numeric(format(date, &quot;%Y&quot;))) |&gt; 
  mutate(month = as.numeric(format(date, &quot;%m&quot;))) |&gt; 
  mutate(day = as.numeric(format(date, &quot;%d&quot;))) |&gt; 
  select(inspection_type, result, date, year, month, day, street_name, zip_code, borough,latitude, longitude, location)</code></pre>
<pre class="r"><code># clean zhvi and zori data
zhvi_tidydf =
  zhvi_df |&gt; 
  janitor::clean_names() |&gt; 
  mutate(region_name=as.numeric(region_name)) |&gt; # Convert the data type to numeric
  rename(zip_code = region_name, county = county_name) |&gt; # Rename &#39;region_name&#39; to &#39;zip_code&#39;
  mutate(county = gsub(&quot; County&quot;, &quot;&quot;, county)) |&gt; 
  pivot_longer(
    cols = starts_with(&quot;x20&quot;), 
    names_to = &quot;date&quot;, 
    values_to = &quot;house_price&quot;) |&gt;  
  mutate(date = as.Date(gsub(&quot;^x&quot;, &quot;&quot;, date), format = &quot;%Y_%m_%d&quot;)) |&gt; # Remove &#39;x&#39; from date and convert to Date format
  mutate(year = as.numeric(format(date, &quot;%Y&quot;))) |&gt; # Extract the year from the date
  mutate(month = as.numeric(format(date, &quot;%m&quot;))) |&gt; # Extract the month from the date
  select(zip_code, county, date, year, month, house_price) |&gt; # Select relevant columns
  drop_na() # Remove rows with missing values for data quality

# Clean and transform ZORI (rental price) dataset
zori_tidydf = 
  zori_df |&gt; 
  janitor::clean_names() |&gt; # Standardize column names to clearer version
  rename(zip_code = region_name, county = county_name) |&gt; # Rename &#39;region_name&#39; to &#39;zip_code&#39;
  mutate(county = gsub(&quot; County&quot;, &quot;&quot;, county)) |&gt; 
  pivot_longer(
    cols = starts_with(&quot;x20&quot;), 
    names_to = &quot;date&quot;, 
    values_to = &quot;rental_price&quot;) |&gt; 
  mutate(date = as.Date(gsub(&quot;^x&quot;, &quot;&quot;, date), format = &quot;%Y_%m_%d&quot;)) |&gt; # Remove &#39;x&#39; from date and convert to Date format
  mutate(year = as.numeric(format(date, &quot;%Y&quot;))) |&gt; 
  mutate(month = as.numeric(format(date, &quot;%m&quot;))) |&gt;
  select(zip_code, county, date, year, month, rental_price) |&gt; # Select necessary columns
  drop_na() # Remove rows with missing values</code></pre>
<pre class="r"><code># zip code df
url = &quot;https://p8105.com/data/zip_codes.html&quot;
zip_code_html = read_html(url)

zip_code_df =
  zip_code_html |&gt; 
  html_table() |&gt; 
  as.data.frame() |&gt; 
  janitor::clean_names() |&gt; 
  mutate(borough = case_when(
    county == &quot;Bronx&quot; ~ &quot;Bronx&quot;,
    county == &quot;Kings&quot; ~ &quot;Brooklyn&quot;,
    county == &quot;New York&quot; ~ &quot;Manhattan&quot;,
    county == &quot;Queens&quot; ~ &quot;Queens&quot;,
    county == &quot;Richmond&quot; ~ &quot;Staten Island&quot;,
    TRUE ~ &quot;Other&quot;
  )) |&gt; 
  select(zip_code, county, neighborhood, borough) |&gt; 
  drop_na()</code></pre>
<pre class="r"><code># merge the zori &amp; zhvi with zip code based on both the `zip_code` and `county`
zori_merged = left_join(zori_tidydf, zip_code_df, by = c(&quot;zip_code&quot;, &quot;county&quot;)) |&gt; 
  select(-date)
zhvi_merged = left_join(zhvi_tidydf, zip_code_df, by = c(&quot;zip_code&quot;, &quot;county&quot;)) |&gt; 
  select(-date)</code></pre>
<pre class="r"><code># merge the zillow information
zillow_merged = merge(zori_merged, zhvi_merged, by = c(&quot;zip_code&quot;, &quot;county&quot;, &quot;borough&quot;, &quot;neighborhood&quot;, &quot;year&quot;, &quot;month&quot;)) |&gt; 
  drop_na()</code></pre>
<pre class="r"><code># define the binary variable of rodent activity
rodent_reg =
  rat_tidydf |&gt; 
  mutate(rodent_bi = case_when(
    result == &quot;Rat Activity&quot; ~ 1,
    TRUE ~ 0
  )) 
head(rodent_reg)</code></pre>
<pre><code>##   inspection_type             result       date year month day      street_name
## 1         Initial             Passed 2023-06-05 2023     6   5        59 STREET
## 2         Initial             Passed 2022-04-05 2022     4   5 SEABREEZE AVENUE
## 3         Initial Failed for Other R 2023-03-14 2023     3  14  EAST 234 STREET
## 4            BAIT       Bait applied 2023-12-26 2023    12  26   JAMAICA AVENUE
## 5         Initial       Rat Activity 2024-01-23 2024     1  23    OXFORD AVENUE
## 6      Compliance             Passed 2022-05-09 2022     5   9    COVERT STREET
##   zip_code  borough latitude longitude                            location
## 1    11377   Queens 40.73837 -73.90647                                    
## 2    11224 Brooklyn 40.57565 -73.97020                                    
## 3    10470    Bronx 40.89732 -73.86322                                    
## 4    11423   Queens 40.71310 -73.76736 (40.713101329334, -73.767362471917)
## 5    10463    Bronx 40.88602 -73.90886 (40.886019879068, -73.908861936068)
## 6    11207 Brooklyn 40.68518 -73.91342                                    
##   rodent_bi
## 1         0
## 2         0
## 3         0
## 4         0
## 5         1
## 6         0</code></pre>
<pre class="r"><code>rodent_reg_merged = 
  left_join(zillow_merged, rodent_reg, by = c(&quot;zip_code&quot;, &quot;borough&quot;, &quot;year&quot;, &quot;month&quot;))
head(rodent_reg_merged)</code></pre>
<pre><code>##   zip_code   county   borough        neighborhood year month rental_price
## 1    10001 New York Manhattan Chelsea and Clinton 2020     1     4088.038
## 2    10001 New York Manhattan Chelsea and Clinton 2020     1     4088.038
## 3    10001 New York Manhattan Chelsea and Clinton 2020     1     4088.038
## 4    10001 New York Manhattan Chelsea and Clinton 2020     1     4088.038
## 5    10001 New York Manhattan Chelsea and Clinton 2020     1     4088.038
## 6    10001 New York Manhattan Chelsea and Clinton 2020     1     4088.038
##   house_price inspection_type       result       date day      street_name
## 1     2417750         Initial Rat Activity 2020-01-24  24 WEST   26 STREET
## 2     2417750      Compliance       Passed 2020-01-07   7        10 AVENUE
## 3     2417750      Compliance Rat Activity 2020-01-07   7   WEST 25 STREET
## 4     2417750         Initial Rat Activity 2020-01-24  24 WEST   26 STREET
## 5     2417750      Compliance       Passed 2020-01-07   7         8 AVENUE
## 6     2417750      Compliance       Passed 2020-01-06   6 WEST   30 STREET
##   latitude longitude                            location rodent_bi
## 1 40.74942 -74.00242 (40.749422696226, -74.002421736205)         1
## 2 40.74844 -74.00361 (40.748437295659, -74.003612700367)         0
## 3 40.74862 -74.00244 (40.748618480914, -74.002436143262)         1
## 4 40.74924 -74.00200 (40.749244294957, -74.001995851746)         1
## 5 40.74940 -73.99548 (40.749395185198, -73.995481352499)         0
## 6 40.74991 -73.99589 (40.749911215466, -73.995885544563)         0</code></pre>
</div>
<div id="data-analysis" class="section level1">
<h1>Data Analysis</h1>
<p><strong>rodent_bi = 1</strong>: Indicates “Rat Activity” was found
during the inspection. This means that there was a confirmed presence of
rodent activity at the inspected location.</p>
<p><strong>rodent_bi = 0</strong>: Indicates “No Rat Activity” or any
other result different from “Rat Activity”. This means there was no
confirmed rodent activity at the inspected location.</p>
<div
id="is-the-rental-price-of-houses-significantly-related-to-the-rodent-activity"
class="section level2">
<h2>Is the rental price of houses significantly related to the rodent
activity?</h2>
<pre class="r"><code># Logistic Regression: Rental Price vs Rodent Activity
model1 &lt;- glm(rodent_bi ~ rental_price, family = binomial, data = rodent_reg_merged)

# Creating Regression Model Table
model1 |&gt;
  broom::tidy() |&gt;
  select(term, estimate, p.value) |&gt;
  knitr::kable(digits = 10)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-0.7659535537</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">rental_price</td>
<td align="right">0.0000779043</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[log[\frac{P(\text{rodent activity} =
1)}{1 - P(\text{rodent activity} = 1)}] = -0.766 + 0.0000779 \times
\text{rental price}\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(P(\text{rodent activity} = 1))\)</span>
is the probability of observing rodent activity.</li>
<li><span class="math inline">\(\text{log}(\frac{P}{1-P})\)</span> is
the log-odds of rodent activity.</li>
</ul>
<p><strong>Intercept (<span
class="math inline">\(\beta_0\)</span>):</strong> -0.766</p>
<p>This represents the log-odds of rodent activity when the rental price
is 0.</p>
<ul>
<li>Since the intercept value is negative (<span
class="math inline">\(\beta_0 = -0.766\)</span>), the log-odds of rodent
activity are less than zero when the rental price is 0.</li>
<li>Odds = <span class="math inline">\(e^{\beta_0} = e^{-0.766} \approx
0.465\)</span>. This implies that, when the rental price is 0, the odds
of rodent activity are approximately 0.465:1, meaning it’s less likely
than not.</li>
</ul>
<p><strong>Coefficient for <code>rental_price</code> (<span
class="math inline">\(\beta_1\)</span>):</strong> 0.0000779</p>
<p>The coefficient represents the change in the log-odds of rodent
activity for a one-unit increase in the rental price.</p>
<ul>
<li>For every one-unit increase in the rental price, the log-odds of
rodent activity increase by 0.0000779.</li>
<li>Odds Ratio = <span class="math inline">\(e^{\beta_1} = e^{0.0000779}
\approx 1\)</span>. This indicates that a small increase in rental price
slightly increases the odds of rodent activity.</li>
</ul>
<p><strong>Statistical Significance:</strong></p>
<p>Both p-values for the intercept and coefficient are &lt;2e-16 <span
class="math inline">\(\approx\)</span> 0, meaning they are statistically
significant at any common significance level (e.g., <span
class="math inline">\(\alpha = 0.05\)</span>). This suggests that both
the intercept and the effect of rental price on rodent activity are
statistically significant.</p>
<p><strong>Summary:</strong></p>
<ul>
<li>Rental price has a statistically significant but very small positive
relationship with rodent activity. While significant, the effect size is
negligible, meaning rental price is not a strong predictor of rodent
activity.</li>
<li>This suggests that other factors likely play a more significant role
in determining rodent activity in the dataset.</li>
</ul>
</div>
<div
id="is-the-value-of-houses-significantly-related-to-the-rodent-activity"
class="section level2">
<h2>Is the value of houses significantly related to the rodent
activity?</h2>
<pre class="r"><code># Logistic Regression: House Value vs Rodent Activity
model2 = glm(rodent_bi ~ house_price, family = binomial, data = rodent_reg_merged)

# Creating Regression Model Table
model2 |&gt;
  broom::tidy() |&gt;
  select(term, estimate, p.value) |&gt;
  knitr::kable(digits = 10)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-0.4510699</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">house_price</td>
<td align="right">-0.0000001</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[log[\frac{P(\text{rodent activity} =
1)}{1 - P(\text{rodent activity} = 1)}] = -0.451 + (-0.0000001) \times
\text{house value}\]</span></p>
<p><strong>Intercept (<span
class="math inline">\(\beta_0\)</span>):</strong> -0.451</p>
<p>This represents the log-odds of rodent activity when the house value
is 0.</p>
<ul>
<li>Since <code>house_price</code> = 0 is unrealistic (as house prices
cannot be zero), the intercept primarily serves as a baseline log-odds
for the model.</li>
<li>Odds = <span class="math inline">\(e^{\beta_0} = e^{-0.451} \approx
0.637\)</span>. This means that the odds of rodent activity are
approximately 0.637:1 when house price is 0 (hypothetically).</li>
</ul>
<p><strong>Coefficient for <code>rental_price</code> (<span
class="math inline">\(\beta_1\)</span>):</strong> -0.0000001</p>
<p>The coefficient indicates the change in log-odds of rodent activity
for a one-unit increase in house price.</p>
<ul>
<li>For each one-unit increase in house price, the log-odds of rodent
activity decrease by 0.0000001.</li>
<li>Odds Ratio = <span class="math inline">\(e^{\beta_1} =
e^{-0.0000001} \approx 1\)</span>. This suggests that an increase in
house price very slightly reduces the odds of rodent activity. However,
the effect size is extremely small and likely negligible in practical
terms.</li>
</ul>
<p><strong>Statistical Significance:</strong></p>
<p>Both p-values for the intercept and coefficient <span
class="math inline">\(\approx\)</span> 0, meaning they are statistically
significant at any common significance level (e.g., <span
class="math inline">\(\alpha = 0.05\)</span>). This means the
relationship between house price and rodent activity is statistically
significant, but the effect size is so small that it has little
practical importance.</p>
<p><strong>Summary:</strong></p>
<ul>
<li>Higher house prices are slightly associated with lower rodent
activity, but the effect is negligible.</li>
<li>While statistically significant, the effect size is so small that
house price is unlikely to be a meaningful predictor of rodent activity.
Other variables are likely more important in explaining the variation in
rodent activity.</li>
</ul>
</div>
<div
id="is-borough-a-confounder-on-the-relationship-between-rodent-activity-and-rental-price-also-between-rodent-activity-and-house-value"
class="section level2">
<h2>Is borough a confounder on the relationship between rodent activity
and rental price? (Also between rodent activity and house value?)</h2>
<div id="is-borough-significantly-related-to-the-rental-price"
class="section level3">
<h3>Is borough significantly related to the rental price?</h3>
<pre class="r"><code>#Linear regression model: rental price and borough
model3 &lt;- lm(rental_price ~ borough, data = rodent_reg_merged)

# Creating Regression Model Table
model3 |&gt;
  broom::tidy() |&gt;
  select(term, estimate, p.value) |&gt;
  knitr::kable(digits = 10)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">2100.02902</td>
<td align="right">0.0000000000</td>
</tr>
<tr class="even">
<td align="left">boroughBrooklyn</td>
<td align="right">805.84709</td>
<td align="right">0.0000000000</td>
</tr>
<tr class="odd">
<td align="left">boroughManhattan</td>
<td align="right">1148.49080</td>
<td align="right">0.0000000000</td>
</tr>
<tr class="even">
<td align="left">boroughQueens</td>
<td align="right">379.75174</td>
<td align="right">0.0000000000</td>
</tr>
<tr class="odd">
<td align="left">boroughStaten Island</td>
<td align="right">45.97548</td>
<td align="right">0.0002538912</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\text{rental price} = 2100.03 +
805.85\times \text{Brooklyn} + 1148.49\times \text{Manhattan} +
379.75\times \text{Queens} + 45.98\times \text{Staten Island}\]</span>
Where:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span>: Intercept (average
rental price in the reference category, Bronx).</li>
<li><span class="math inline">\(\beta_{1,2,3,4}\)</span>: Coefficients
for the borough dummy variables. These represent the difference in
average rental price between each borough and the Bronx.</li>
</ul>
<p><strong>Intercept (<span
class="math inline">\(\beta_0\)</span>):</strong> 2100.03</p>
<p>This represents the average rental price in the Bronx (the reference
borough).</p>
<p><strong>Coefficient for borough (<span
class="math inline">\(\beta_{1,2,3,4}\)</span>):</strong></p>
<p>This indicates how much the average rental price in each borough
(Brooklyn, Manhattan, Queens, Staten Island) is higher than in the
Bronx. All are positive.</p>
<p><strong>Statistical Significance:</strong></p>
<p>The overall p-value for the model (p &lt; 2e-16) indicates that
borough is significantly related to rental price. The p-values for each
borough relative to the reference category (Bronx) are all statistically
significant (p &lt; 0.001), meaning rental prices differ significantly
across boroughs.</p>
<p><strong>Summary:</strong></p>
<p>Borough is significantly related to rental price, with notable
differences in average rental prices across boroughs.</p>
</div>
<div id="is-borough-significantly-related-to-the-rodent-activity"
class="section level3">
<h3>Is borough significantly related to the rodent activity?</h3>
<pre class="r"><code>#Regression model: rodent activity and borough
model4 &lt;- glm(rodent_bi ~ borough, data = rodent_reg_merged)

# Creating Regression Model Table
model4 |&gt;
  broom::tidy() |&gt;
  select(term, estimate, p.value) |&gt;
  knitr::kable(digits = 10)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.44100985</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">boroughBrooklyn</td>
<td align="right">-0.08470251</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">boroughManhattan</td>
<td align="right">-0.03503736</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">boroughQueens</td>
<td align="right">-0.16305830</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">boroughStaten Island</td>
<td align="right">-0.34428366</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\text{rodent
activity}=0.441+(−0.0847)\times \text{Brooklyn}+(−0.0350)\times
\text{Manhattan}+(−0.1631)\text{Queens}+(−0.3443)\times
\text{StatenIsland}\]</span> Where:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span>: Intercept (baseline
probability of rodent activity in the reference borough, Bronx).</li>
<li><span class="math inline">\(\beta_{1,2,3,4}\)</span>: Coefficients
representing the difference in rodent activity between each borough and
the Bronx.</li>
</ul>
<p><strong>Intercept (<span
class="math inline">\(\beta_0\)</span>):</strong> 0.441</p>
<p>This represents the baseline probability of rodent activity in the
Bronx (the reference category).</p>
<p><strong>Coefficient for borough (<span
class="math inline">\(\beta_{1,2,3,4}\)</span>):</strong></p>
<p>The coefficient for each borough (Brooklyn, Manhattan, Queens, Staten
Island) represents the difference in the average probability of rodent
activity between each borough and the Bronx. For example, the
probability of rodent activity in Brooklyn is 0.0847 lower than in the
Bronx.</p>
<p><strong>Statistical Significance:</strong></p>
<p>All coefficients, including the intercept, have p &lt; 0.001,
indicating that the differences in rodent activity probabilities across
boroughs are statistically significant.</p>
<p><strong>Summary:</strong></p>
<p>Borough is significantly related to rodent activity.</p>
</div>
<div id="regression-model-with-both-borough-and-rental-price"
class="section level3">
<h3>Regression model with both borough and rental price</h3>
<pre class="r"><code>#Regression model testing for confounding
model5 &lt;- glm(rodent_bi ~ borough + rental_price, data = rodent_reg_merged)

# Creating Regression Model Table
model5 |&gt;
  broom::tidy() |&gt;
  select(term, estimate, p.value) |&gt;
  knitr::kable(digits = 10)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.4179050705</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">boroughBrooklyn</td>
<td align="right">-0.0935738820</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="odd">
<td align="left">boroughManhattan</td>
<td align="right">-0.0476417252</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">boroughQueens</td>
<td align="right">-0.1672550224</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="odd">
<td align="left">boroughStaten Island</td>
<td align="right">-0.3447959091</td>
<td align="right">0.00e+00</td>
</tr>
<tr class="even">
<td align="left">rental_price</td>
<td align="right">0.0000110014</td>
<td align="right">6.13e-08</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\text{rodent acticvity} =
0.4179+(−0.0936)\times \text{Brooklyn}+(−0.0476)\times
\text{Manhattan}+(−0.1673)\times \text{Queens}+(−0.3448)\times
\text{Staten Island}+(0.000011)\times \text{rental price}\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\beta_0:\)</span> Intercept (baseline
probability of rodent activity in the Bronx with rental price = 0).</li>
<li><span class="math inline">\(\beta_{1,2,3,4}:\)</span> Coefficients
for boroughs (relative to Bronx).</li>
<li><span class="math inline">\(\beta_5:\)</span> Coefficient for rental
price, indicating how rental price impacts rodent activity.</li>
</ul>
<p><strong>Intercept (<span
class="math inline">\(\beta_0\)</span>):</strong> 0.4179</p>
<p>The intercept represents the baseline probability of rodent activity
in the Bronx when rental price is 0.</p>
<p><strong>Coefficient for borough (<span
class="math inline">\(\beta_{1,2,3,4}\)</span>):</strong></p>
<p>These coefficients represent the difference in probability of rodent
activity between each borough and the Bronx (the reference borough).</p>
<p><strong>Coefficient for borough (<span
class="math inline">\(\beta_{5}\)</span>):</strong> 0.000011</p>
<p>Rental price has a small positive effect on the probability of rodent
activity.</p>
<p><strong>Statistical Significance:</strong></p>
<p>All predictors, including boroughs and rental price, are
statistically significant (p &lt; 0.001). This suggests that both
borough and rental price significantly contribute to the prediction of
rodent activity.</p>
<p><strong>Summary:</strong></p>
<p>Borough remains a strong predictor of rodent activity. Rental price
is also a significant predictor.</p>
</div>
<div id="is-borough-significantly-related-to-the-house-value"
class="section level3">
<h3>Is borough significantly related to the house value?</h3>
<pre class="r"><code>#Linear regression model: house value and borough
model6 &lt;- lm(house_price ~ borough, data = rodent_reg_merged)

# Creating Regression Model Table
model6 |&gt;
  broom::tidy() |&gt;
  select(term, estimate, p.value) |&gt;
  knitr::kable(digits = 10)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">434080.5</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">boroughBrooklyn</td>
<td align="right">517358.1</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">boroughManhattan</td>
<td align="right">759697.9</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">boroughQueens</td>
<td align="right">303134.7</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">boroughStaten Island</td>
<td align="right">216711.8</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\text{house value} =
434080.5+517358.1\times \text{Brooklyn}+759697.9\times
\text{Manhattan}+303134.7\times \text{Queens}+216711.8\times
\text{StatenIsland}\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span>: Intercept (average
rental price in the reference category, Bronx).</li>
<li><span class="math inline">\(\beta_{1,2,3,4}\)</span>: Coefficients
for the borough dummy variables, indicating differences in house value
relative to the Bronx.</li>
</ul>
<p><strong>Intercept (<span
class="math inline">\(\beta_0\)</span>):</strong> 434080.5</p>
<p>The intercept represents the average house value in the Bronx (the
reference category).</p>
<p><strong>Coefficient for borough (<span
class="math inline">\(\beta_{1,2,3,4}\)</span>):</strong></p>
<p>These coefficients indicate how much higher the average house value
is in each borough compared to the Bronx. All positive.</p>
<p><strong>Statistical Significance:</strong></p>
<p>All borough coefficients (<span class="math inline">\(p\approx
0\)</span>) are statistically significant, indicating significant
differences in average house values between the Bronx and other
boroughs. The overall model is significant, meaning that borough is a
significant predictor of house value.</p>
<p><strong>Summary:</strong></p>
<p>Borough is significantly related to house value, reflecting
differences in property markets across New York City.</p>
</div>
<div id="regression-model-with-both-borough-and-house-value"
class="section level3">
<h3>Regression model with both borough and house value</h3>
<pre class="r"><code>#Regression model testing for confounding
model7 &lt;- glm(rodent_bi ~ borough + house_price, data = rodent_reg_merged)

# Creating Regression Model Table
model7 |&gt;
  broom::tidy() |&gt;
  select(term, estimate, p.value) |&gt;
  knitr::kable(digits = 10)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.4625980364</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">boroughBrooklyn</td>
<td align="right">-0.0589711698</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">boroughManhattan</td>
<td align="right">0.0027349667</td>
<td align="right">0.5799593</td>
</tr>
<tr class="even">
<td align="left">boroughQueens</td>
<td align="right">-0.1479732293</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">boroughStaten Island</td>
<td align="right">-0.3335062504</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">house_price</td>
<td align="right">-0.0000000497</td>
<td align="right">0.0000000</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\text{rodent activity} =
0.4626+(−0.0590)\times \text{Brooklyn}+(0.0027)\times
\text{Manhattan}+(−0.1480)\times \text{Queens}+(−0.3335)\times
\text{Staten Island}+(−0.000000497)\times \text{house
price}\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\beta_0:\)</span> Intercept, the
baseline probability of rodent activity in the Bronx with house price =
0.</li>
<li><span class="math inline">\(\beta_{1,2,2,4}:\)</span> Coefficients
for boroughs (compared to the Bronx).</li>
<li><span class="math inline">\(\beta_5:\)</span> Coefficient for house
price, representing the effect of house price on rodent activity.</li>
</ul>
<p><strong>Intercept (<span
class="math inline">\(\beta_0\)</span>):</strong> 0.4626</p>
<p>The intercept represents the baseline probability of rodent activity
in the Bronx (the reference category) when the house price is 0.</p>
<p><strong>Coefficient for borough (<span
class="math inline">\(\beta_{1,2,3,4}\)</span>):</strong></p>
<p>These coefficients represent the difference in the probability of
rodent activity for each borough compared to the Bronx, controlling for
house price.</p>
<p><strong>Coefficient for borough (<span
class="math inline">\(\beta_{5}\)</span>):</strong> -0.000000497</p>
<p>House price has a very small negative effect on the probability of
rodent activity.</p>
<p><strong>Statistical Significance:</strong></p>
<p>Manhattan is not statistically significant (p = 0.58), but all other
borough coefficients are statistically significant (p &lt; 0.001). The
coefficient for house price is statistically significant, but the effect
size is negligible.</p>
<p><strong>Summary:</strong></p>
<p>Borough remains a significant predictor of rodent activity. House
price also has a statistically significant effect.</p>
</div>
<div id="regression-model-with-borough-rental-price-and-house-value"
class="section level3">
<h3>Regression model with borough, rental price, and house value</h3>
<pre class="r"><code>#Regression model testing for confounding
model8 &lt;- glm(rodent_bi ~ borough + rental_price + house_price, data = rodent_reg_merged)

# Creating Regression Model Table
model8 |&gt;
  broom::tidy() |&gt;
  select(term, estimate, p.value) |&gt;
  knitr::kable(digits = 10)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.3864155486</td>
<td align="right">0.000000000</td>
</tr>
<tr class="even">
<td align="left">boroughBrooklyn</td>
<td align="right">-0.0713618975</td>
<td align="right">0.000000000</td>
</tr>
<tr class="odd">
<td align="left">boroughManhattan</td>
<td align="right">-0.0136966681</td>
<td align="right">0.006363476</td>
</tr>
<tr class="even">
<td align="left">boroughQueens</td>
<td align="right">-0.1510194546</td>
<td align="right">0.000000000</td>
</tr>
<tr class="odd">
<td align="left">boroughStaten Island</td>
<td align="right">-0.3252400123</td>
<td align="right">0.000000000</td>
</tr>
<tr class="even">
<td align="left">rental_price</td>
<td align="right">0.0000462109</td>
<td align="right">0.000000000</td>
</tr>
<tr class="odd">
<td align="left">house_price</td>
<td align="right">-0.0000000978</td>
<td align="right">0.000000000</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\text{rodent activity} =
0.3864+(−0.0714)\times \text{Brooklyn}+(−0.0137)\times
\text{Manhattan}+(−0.1510)\times \text{Queens}+(−0.3252)\times
\text{Staten Island}+(0.0000462)\times \text{rental
price}+(−0.000000978)\times \text{house price}\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\beta_0:\)</span> Intercept,
representing the baseline probability of rodent activity in the Bronx
with rental price = 0 and house price = 0.</li>
<li><span class="math inline">\(\beta_{1,2,3,4}:\)</span> Coefficients
for boroughs (relative to the Bronx).</li>
<li><span class="math inline">\(\beta_5:\)</span> Coefficient for rental
price, representing the effect of rental price on rodent activity.</li>
<li><span class="math inline">\(\beta_6:\)</span> Coefficient for house
price, representing the effect of house price on rodent activity.</li>
</ul>
<p><strong>Intercept (<span
class="math inline">\(\beta_0\)</span>):</strong> 0.3864</p>
<p>The intercept represents the baseline probability of rodent activity
in the Bronx when rental_price=0 and house_price=0.</p>
<p><strong>Coefficient for borough (<span
class="math inline">\(\beta_{1,2,3,4}\)</span>):</strong></p>
<p>These coefficients represent the difference in the probability of
rodent activity for each borough compared to the Bronx, controlling for
rental price and house price.</p>
<p><strong>Coefficient for borough (<span
class="math inline">\(\beta_{5}\)</span>):</strong> 0.0000462</p>
<p>Rental price has a very small positive effect on the probability of
rodent activity.</p>
<p><strong>Coefficient for borough (<span
class="math inline">\(\beta_{6}\)</span>):</strong> -0.000000978</p>
<p>House price has a very small negative effect on the probability of
rodent activity.</p>
<p><strong>Statistical Significance:</strong></p>
<p>All borough coefficients are statistically significant (p&lt;0.01).
Rental price and house price are statistically significant (p=0), but
their effects are very small.</p>
<p><strong>Summary:</strong></p>
<p>Borough is a strong predictor of rodent activity. Rental price and
house price are also statistically significant.</p>
<p><strong>In conclusion, Borough remains the dominant predictor of
rodent activity in the model. Although rental price and house price are
statistically significant, their effects are too small to have practical
relevance. Here, we need to compare the models to decide which
predictors to consider.</strong></p>
</div>
<div
id="comparison-of-models-including-rental-price-and-house-value-and-excluding-rental-price-and-house-value"
class="section level3">
<h3>Comparison of models including rental price and house value, and
excluding rental price and house value</h3>
<pre class="r"><code>cv1_df = 
  crossv_mc(rodent_reg_merged, 100)

cv1_df |&gt; 
  mutate(
    mod_1  = map(train, \(df) glm(rodent_bi ~ borough, data = rodent_reg_merged)),
    mod_2  = map(train, \(df) glm(rodent_bi ~ borough + rental_price + house_price, 
                                  data = rodent_reg_merged))) |&gt; 
  mutate(
    rmse_1 = map2_dbl(mod_1, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_2 = map2_dbl(mod_2, test, \(mod, df) rmse(model = mod, data = df))) |&gt;
  select(starts_with(&quot;rmse&quot;)) |&gt;
  pivot_longer(
    everything(), 
    names_to = &quot;model&quot;, 
    values_to = &quot;rmse&quot;, 
    names_prefix = &quot;rmse_&quot;) |&gt;
  ggplot(aes(x = model, y = rmse, group = model, fill = model)) + 
  geom_violin(alpha = 0.5) +
  theme_minimal()</code></pre>
<p><img
src="regression_models_files/figure-gfm/unnamed-chunk-18-1.png" /><!-- --></p>
<p>The model excluding rental price and house value has a much higher
root mean squared errors (RMSE) value than the model including rental
price and house value. This means that the <strong>model including
rental price and house value</strong> better fits our data.</p>
</div>
</div>
<div
id="testing-for-interaction-between-rental-price-house-value-and-borough"
class="section level2">
<h2>Testing for Interaction between rental price, house value, and
borough</h2>
<p>The p-value for the interaction term (p = 0.9736) indicates that the
interaction between rental price and house price does not significantly
affect the probability of rodent activity.</p>
<pre class="r"><code>#Regression model testing for confounding
model9 = glm(formula = rodent_bi ~ borough + rental_price + house_price + 
              borough*rental_price*house_price, data = rodent_reg_merged)

# Creating Regression Model Table
model9 |&gt;
  broom::tidy() |&gt;
  select(term, estimate, p.value) |&gt;
  knitr::kable(digits = 10)</code></pre>
<table>
<colgroup>
<col width="62%" />
<col width="20%" />
<col width="17%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.6955330911</td>
<td align="right">0.000000000</td>
</tr>
<tr class="even">
<td align="left">boroughBrooklyn</td>
<td align="right">-1.4197603991</td>
<td align="right">0.000000000</td>
</tr>
<tr class="odd">
<td align="left">boroughManhattan</td>
<td align="right">0.0063149166</td>
<td align="right">0.934697252</td>
</tr>
<tr class="even">
<td align="left">boroughQueens</td>
<td align="right">-0.2337439883</td>
<td align="right">0.062390602</td>
</tr>
<tr class="odd">
<td align="left">boroughStaten Island</td>
<td align="right">-2.9077449660</td>
<td align="right">0.044424454</td>
</tr>
<tr class="even">
<td align="left">rental_price</td>
<td align="right">-0.0000035076</td>
<td align="right">0.917536797</td>
</tr>
<tr class="odd">
<td align="left">house_price</td>
<td align="right">-0.0000004249</td>
<td align="right">0.008070334</td>
</tr>
<tr class="even">
<td align="left">boroughBrooklyn:rental_price</td>
<td align="right">0.0003818638</td>
<td align="right">0.000000000</td>
</tr>
<tr class="odd">
<td align="left">boroughManhattan:rental_price</td>
<td align="right">-0.0000618627</td>
<td align="right">0.071637366</td>
</tr>
<tr class="even">
<td align="left">boroughQueens:rental_price</td>
<td align="right">-0.0000368845</td>
<td align="right">0.488734039</td>
</tr>
<tr class="odd">
<td align="left">boroughStaten Island:rental_price</td>
<td align="right">0.0013601407</td>
<td align="right">0.065178956</td>
</tr>
<tr class="even">
<td align="left">boroughBrooklyn:house_price</td>
<td align="right">0.0000011302</td>
<td align="right">0.000000000</td>
</tr>
<tr class="odd">
<td align="left">boroughManhattan:house_price</td>
<td align="right">0.0000002448</td>
<td align="right">0.128552047</td>
</tr>
<tr class="even">
<td align="left">boroughQueens:house_price</td>
<td align="right">-0.0000000407</td>
<td align="right">0.838245302</td>
</tr>
<tr class="odd">
<td align="left">boroughStaten Island:house_price</td>
<td align="right">0.0000034063</td>
<td align="right">0.123142293</td>
</tr>
<tr class="even">
<td align="left">rental_price:house_price</td>
<td align="right">-0.0000000001</td>
<td align="right">0.332989979</td>
</tr>
<tr class="odd">
<td align="left">boroughBrooklyn:rental_price:house_price</td>
<td align="right">-0.0000000002</td>
<td align="right">0.015165596</td>
</tr>
<tr class="even">
<td align="left">boroughManhattan:rental_price:house_price</td>
<td align="right">0.0000000001</td>
<td align="right">0.157520150</td>
</tr>
<tr class="odd">
<td align="left">boroughQueens:rental_price:house_price</td>
<td align="right">0.0000000002</td>
<td align="right">0.013981259</td>
</tr>
<tr class="even">
<td align="left">boroughStaten Island:rental_price:house_price</td>
<td align="right">-0.0000000017</td>
<td align="right">0.116823631</td>
</tr>
</tbody>
</table>
<p>There are significant interactions between borough and rental price
as well as borough and house price, particularly in Brooklyn and Queens.
This indicates that the relationship between rental price, house price,
and rodent activity varies across different boroughs.</p>
<p>This model is considerably more complex, with numerous interaction
terms. The results suggest that while borough remains a key factor in
predicting rodent activity, the influence of rental and house prices
varies by borough. However, many of the interaction effects are not
statistically significant, implying that the added complexity may not be
providing substantial predictive improvement.</p>
<p>Therefore, we need to check further.</p>
</div>
<div
id="comparison-of-income-including-models-with-and-without-interaction-term"
class="section level2">
<h2>Comparison of income including models with and without interaction
term:</h2>
<pre class="r"><code>cv2_df = 
  crossv_mc(rodent_reg_merged, 100) 

cv2_df |&gt; 
  mutate(
    mod_1  = map(train, \(df) glm(formula = rodent_bi ~ borough + rental_price + house_price 
                                  + borough*rental_price*house_price, data = rodent_reg_merged)),
    mod_2  = map(train, \(df) glm(formula = rodent_bi ~ borough + rental_price + house_price, 
                                  data = rodent_reg_merged))) |&gt; 
  mutate(
    rmse_1 = map2_dbl(mod_1, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_2 = map2_dbl(mod_2, test, \(mod, df) rmse(model = mod, data = df))) |&gt;
  select(starts_with(&quot;rmse&quot;)) |&gt;
  pivot_longer(
    everything(), 
    names_to = &quot;model&quot;, 
    values_to = &quot;rmse&quot;, 
    names_prefix = &quot;rmse_&quot;) |&gt;
  ggplot(aes(x = model, y = rmse, group = model, fill = model)) + 
  geom_violin()</code></pre>
<p><img
src="regression_models_files/figure-gfm/unnamed-chunk-20-1.png" /><!-- --></p>
<p>The model with an interaction term between borough, rental price, and
home value has a lower RMSE value than the model without an interaction
term. Ultimately, the model with interaction terms appears to be the
best model.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
